spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: stmp.gmail.com
    port: 587
    username: imadhajali66@gmail.com
    password: kzbxlrakolmxmjwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
