spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mail:
    host: stmp.gmail.com
    port: 587
    username: imadhajali66@gmail.com
    password: kzbxlrakolmxmjwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
